### ISSUE TITLE
ATACseq, Session 3 - Identifying Motifs in ATAC

### ISSUE THREAD

**Issue by guidoputignano** [RockefellerUniversity/RU_ATACseq#3]
Dear @ThomasCarroll, 
when looking at the third tutorial, I wasn't sure if the code

> load("data/myCounts.RData")
> myCounts
> peakRanges <- rowRanges(myCounts)
> peakRanges[1, ]

can also come from what we did in the second tutorial. If it's not the case, how can we adapt the code?

> peaks <- dir("/Users/guidoputignano/Research/stat426/Project/Main/ATACseq/peaks", pattern = "*.narrowPeak", 
>     full.names = TRUE)
> myPeaks <- lapply(peaks, ChIPQC:::GetGRanges, simple = TRUE)

**Comment by matthew-paul-2006** [comment]
Hi Guido,

Both processes should work, though the second approach needs a little extra. Ultimately you just want to be able to get your consensus peaks into a GRange object. You can do that by reading in the narrowPeaks objects and recreating the consensus or you can load the counts object which has these consensus peaks associated with it. 

The additional steps you need are the creation of the consensus. Currently, you would have a list of peaks in the *myPeaks* object. From this you would need to make the nonredundant peaks and then the consensus peaks, as you did in session 2. By doing option 1, we shorten the amount of code we need to put together, so that is why we show how to do it that way.
